### ISSUE TITLE
Does EMPIAR have a manifest or other straightforward way to discover all files in the catalog?

### ISSUE THREAD

**Issue by ots22** [alan-turing-institute/empiarreader#30]

**Comment by JatGreer** [comment]
Summary of  meeting with Matt Iadanza:
- EMPIAR .sch and associated EMPIAR API https://www.ebi.ac.uk/empiar/api/documentation/ **SHOULD** be sufficient for this but ISN'T because of poor metadata entry standards during deposition of many entries
- One solution is to create a list of all known-compliant EMPIAR entries and only allow Empiarreader to use those, but has major disadvantage of inflexibility and limiting usage of the tool. So probably not the way forward?
- Next step is to get in touch with EMPIAR contact (M. Iadanza offered to put us in touch soon) to figure out how they show the file directory structure of EMPIAR website (and web-interface of their ftp)
- If no optimal solution is found from that, an alternative is to implement an ftp-parser/scraper which returns the full directory and file structure of a given EMPIAR entry and can be used in conjunction with user-supplied wildcard/regexp path to select files/directories for indiviudual download

**Comment by JatGreer** [comment]
Method for searching EMPIAR archive via:
- entry # 
- dir path (optional)
- wildcard/regexp path 
is implemented in #33 on command line

Please review whether this closes this issue
